# Generated by Django 6.0.1 on 2026-04-18 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_course_profile_is_approved_activitylog_assignment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_approved',
        ),
    ]
